"""sensor_nodes: api_key_hash for node authentication

Revision ID: b181c764df90
Revises: f0c9c93c7c21
Create Date: 2026-09-29 13:08:10.602689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b181c764df90'
down_revision: Union[str, Sequence[str], None] = 'f0c9c93c7c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_nodes', sa.Column('api_key_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_nodes', 'api_key_hash')
    # ### end Alembic commands ###
