"""initial schema: 10 tables

Revision ID: d0ed9462fca9
Revises: 
Create Date: 2026-09-21 15:37:55.487313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0ed9462fca9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmers',
    sa.Column('farmer_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('farm_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('farmer', 'admin')", name='ck_farmers_role'),
    sa.PrimaryKeyConstraint('farmer_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('weather_readings',
    sa.Column('weather_id', sa.String(length=32), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('forecast_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("source IN ('archive', 'historical_forecast', 'forecast')", name='ck_weather_readings_source'),
    sa.PrimaryKeyConstraint('weather_id'),
    sa.UniqueConstraint('source', 'latitude', 'longitude', 'timestamp', 'forecast_issued_at', name='uq_weather_readings_source_point_time', postgresql_nulls_not_distinct=True)
    )
    op.create_table('leaf_images',
    sa.Column('image_id', sa.String(length=32), nullable=False),
    sa.Column('farmer_id', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('capture_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.farmer_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('sensor_nodes',
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('farmer_id', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('last_sync_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.farmer_id'], ),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('diagnosis_results',
    sa.Column('result_id', sa.String(length=32), nullable=False),
    sa.Column('image_id', sa.String(length=32), nullable=False),
    sa.Column('disease_label', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('probabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_score_used', sa.Float(), nullable=False),
    sa.Column('threshold_used', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('late_blight_flagged', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_level IN ('low', 'medium', 'high')", name='ck_diagnosis_results_risk_level'),
    sa.ForeignKeyConstraint(['image_id'], ['leaf_images.image_id'], ),
    sa.PrimaryKeyConstraint('result_id'),
    sa.UniqueConstraint('image_id')
    )
    op.create_table('risk_scores',
    sa.Column('score_id', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('data_source', sa.String(length=10), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('hutton_day', sa.Boolean(), nullable=True),
    sa.Column('hutton_period', sa.Boolean(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('for_date', sa.Date(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_source IN ('sensor', 'api')", name='ck_risk_scores_data_source'),
    sa.CheckConstraint("method IN ('hutton', 'learned')", name='ck_risk_scores_method'),
    sa.CheckConstraint('horizon_hours IN (0, 24, 48)', name='ck_risk_scores_horizon_hours'),
    sa.CheckConstraint('score >= 0 AND score <= 1', name='ck_risk_scores_score_range'),
    sa.ForeignKeyConstraint(['node_id'], ['sensor_nodes.node_id'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    op.create_table('sensor_readings',
    sa.Column('reading_id', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('leaf_wetness', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['sensor_nodes.node_id'], ),
    sa.PrimaryKeyConstraint('reading_id'),
    sa.UniqueConstraint('node_id', 'timestamp', name='uq_sensor_readings_node_timestamp')
    )
    op.create_table('symptom_reports',
    sa.Column('report_id', sa.String(length=32), nullable=False),
    sa.Column('farmer_id', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('onset_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.farmer_id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['sensor_nodes.node_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('result_id', sa.String(length=32), nullable=True),
    sa.Column('risk_score_id', sa.String(length=32), nullable=True),
    sa.Column('alert_type', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivery_status', sa.String(length=30), nullable=False),
    sa.Column('provider_message_id', sa.String(length=100), nullable=True),
    sa.CheckConstraint("alert_type IN ('high_risk', 'diagnosis', 'low_risk')", name='ck_alerts_alert_type'),
    sa.ForeignKeyConstraint(['node_id'], ['sensor_nodes.node_id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['diagnosis_results.result_id'], ),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.score_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('reading_contributions',
    sa.Column('reading_id', sa.String(length=32), nullable=False),
    sa.Column('result_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['reading_id'], ['sensor_readings.reading_id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['diagnosis_results.result_id'], ),
    sa.PrimaryKeyConstraint('reading_id', 'result_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_contributions')
    op.drop_table('alerts')
    op.drop_table('symptom_reports')
    op.drop_table('sensor_readings')
    op.drop_table('risk_scores')
    op.drop_table('diagnosis_results')
    op.drop_table('sensor_nodes')
    op.drop_table('leaf_images')
    op.drop_table('weather_readings')
    op.drop_table('farmers')
    # ### end Alembic commands ###
